### ISSUE TITLE
Drops not posting to Discord

### ISSUE THREAD

**Issue by Hentiny** [RinZJ/better-discord-loot-logger#13]
Can't get this plugin to work at all.

Tried a few webhooks, different valuable drop thresholds, different item sources (various NPCs and barrows). Also tried installing the plugin a few times and restarting RuneLite to no avail.

**Comment by MythicWebsite** [comment]
I am also having this issue. Cannot get it to work at all.

**Comment by GaryGooch** [comment]
Yup same, dead plugin.

**Comment by iProdigy** [comment]
This plugin doesn't catch all loot sources because it doesn't monitor the following events: `NpcLootReceived`, `PlayerLootReceived`, and `LootReceived`.

The loot notifier in [Dink](https://github.com/pajlads/DinkPlugin) *does* cover these events & may fit your needs better (disclaimer: I am a maintainer of that plugin)

**Comment by RinZJ** [comment]
As @iProdigy has mentioned it doesn't actually monitor loot received events, it is mainly only looking at chat messages for drops/values. Most likely if it isn't working it will be because the loot doesn't show up in chat or you have chat messages disabled for loot/collection log items.
