### ISSUE TITLE
Questions about plugin

### ISSUE THREAD

**Issue by BossHuso** [RinZJ/better-discord-loot-logger#3]
Hi there,

I'm currently maintaining the plugin "Discord Rare Drop Notifier" in the plugin hub and recently saw this plugin being added into RL.

Since this plugins purpose the same, I'm guessing it could be confusing for users in RL. Would you be open to merge the plugins and contribute to the existing plugin instead of this one? As far as I can see the only thing the existing plugin doesn't do is send collection log information.

Would be a shame if we actively develop in two different plugins. Might as well work together on the plugin with 5k+ active installs :)

Thanks and have a nice day!

**Comment by RinZJ** [comment]
Sorry for the super late reply on this, kind of just made this plugin for myself so haven't payed much attention to it but more than happy for you to merge it into yours. I don't have the time at the moment but I have no issue if you wanna just rip the code for the collection log option and add to yours

Let me know if/when you do and I'll remove this plugin since I agree, there isn't any need for 2 that do the same thing.
